$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
description: Custom environment for Training
name: aml-training-project
version: 0.1.3

conda_file: ../components/training/conda.yaml
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
os_type: linux

tags:
  Pillow: 11.2.1
  torch: 2.2.0